### ISSUE TITLE
ESPHome integration

### ISSUE THREAD

**Issue by ManuInNZ** [BinaryTechLabs/HA-Docker-Files#1]
Hi there

Thank you very much for the repo and video.
I have a question though on how to successfully register ESPHome devices in Home Assistant in this setup.

I managed to get the ESPHome devices recognised after adding the `ESPHOME_DASHBOARD_USE_PING=true` as environment var but still can't get to disccover the ESPHome devices in HA..

Any clue to what I am missing?

Cheers

**Comment by BinaryTechLabs** [comment]
Hey there,

I sincerely apologize for the extremely delayed response to your question, and I appreciate your patience.

Regarding the issue you've encountered with registering ESPHome devices in Home Assistant, you're on the right track with the **ESPHOME_DASHBOARD_USE_PING** environment variable. However, to enable successful registration, you also need to ensure that your ESPHome devices are configured to use the Home Assistant API.

```yaml
# Enable Home Assistant API
api:
  encryption:
    key: "baEkB/gCfWeARozMHG2nXNDSS//XvRIAz5HcjhjfXo0="
```

This configuration enables the Home Assistant API on your ESPHome device, allowing it to communicate with Home Assistant and get "seen". Make sure this section is present in the YAML configuration for each ESPHome device you want to integrate.

If you've already added this section and are still facing issues, double-check the key and ensure that it matches the key configured in Home Assistant.

Again, I apologize for the delay, and I hope this resolves your concern. If you have any further questions or run into more issues, feel free to ask.

Cheers! 🏡✨
